### ISSUE TITLE
Additional css classes to BootstrapDialog.confirm

### ISSUE THREAD

**Issue by ElyeM** [nakupanda/bootstrap3-dialog#164] opened 2015-07-02 16:09 UTC
Is there a way to add  `cssClass:` to BootstrapDialog.confirm ?
I can add `cssClass:` only within BootstrapDialog.show but not within BootstrapDialog.confirm.

Any solution ?

```javascript
BootstrapDialog.confirm({
            title: 'WARNING',
            message: 'Warning! Drop your banana?',
            type: BootstrapDialog.TYPE_WARNING,
            cssClass: 'myClass', //Not Working
        });
```

**Comment by nakupanda** [comment] 2015-07-15 01:46
Yes... this won't work, parameters inside BootstrapDialog.confirm are almost hardcoded.

Please try

````
BootstrapDialog.configDefaultOptions({
    cssClass: 'some-classes'
});
BootstrapDialog.confirm({
            title: 'WARNING',
            message: 'Warning! Drop your banana?',
            type: BootstrapDialog.TYPE_WARNING,
        });
````

But this will affect all subsequent dialogs

**Comment by nakupanda** [comment] 2015-08-19 07:05
Closing this one, reopen when feedback is received.

**Closed by nakupanda** 2015-08-19 07:05 UTC

**Comment by ElyeM** [comment] 2015-10-27 19:36
Yup, adding this snippet helps.

```javascript
BootstrapDialog.configDefaultOptions({
    cssClass: 'some-classes'
});
```

Thanks,

**Comment by nakupanda** [comment] 2015-10-28 09:06
No problem :)

**Comment by CramUojdab** [comment] 2016-01-28 13:39
Hello,

Back with this issue, i write this class : 

			.paper {
				    text-transform: uppercase;
				    border: none;
				    -webkit-box-shadow: 1px 1px 4px rgba(0, 0, 0, 0.4);
				    box-shadow: 1px 1px 4px rgba(0, 0, 0, 0.4);
				    -webkit-transition: all 0.4s;
				    -o-transition: all 0.4s;
				    transition: all 0.4s;
				}

and then in the JS :+1: 
						BootstrapDialog.configDefaultOptions({
						    cssClass: 'paper'
						});		

But nothing happend ...

Any idea ?

**Comment by nakupanda** [comment] 2016-01-29 03:08
See here http://jsfiddle.net/uw1e3zve/1/

At least the characters are in uppercase.

**Comment by CramUojdab** [comment] 2016-01-29 08:27
Ok got it.

The issue is that i will use another style sheet complementary at bootsrap.min.css (http://bootswatch.com/paper/#buttons) but the colors are different for buttons and modal header.
