### ISSUE TITLE
Page scrolle (jumps) to top on model show

### ISSUE THREAD

**Issue by saqueib** [nakupanda/bootstrap3-dialog#183] opened 2015-09-01 11:44 UTC
I don't know what is the issue but when I click a button to open the dialog, page scrolls to top. Its quite annoying every time you have to scroll back 

Here is what i have used to call 

**HTML**
```html
<a href="#" class="delete-btn">Delete</a>
```

**JS**
```js
   $('.delete-btn').on('click', function(e) {
        e.preventDefault();
        BootstrapDialog.confirm('are you sure? it will be gone', function(answer){
            if(answer) {
                //delete it 
            }
        });
   });
```
Please help, what could be the issue

**Comment by saqueib** [comment] 2015-09-02 16:02
I found the issue, its related a css. But i cant understand why its doing it. If someone can tell how its affecting will be cool.

```html
html {
       overflow-y: scroll; //removed this and its fixed
}

**Comment by assertnotnull** [comment] 2015-09-15 16:26
What makes it jump up is the href="#". That's a valid unnamed anchor but there is none in page to jump to so it jumps to the top.
Short solution: replace your href="#" with javascript:void(0), it prevents moving. For more information see 
http://stackoverflow.com/questions/134845/href-attribute-for-javascript-links-or-javascriptvoid0

Or even since it's bootstrap change your <a> for a <button> so you don't need the href at all.
Either way, that's not a bug for that plugin nor bootstrap. You can reproduce that moving behavior using simple html.

**Comment by saqueib** [comment] 2015-09-16 02:39
@assertnotnull I know what `#` does but as you can see i have prevented default `e.preventDefault();`, URL never changes to `#`, it was due to css property which is used to always show the vertical scroll-bar

```html {
       overflow-y: scroll; //removed this and its fixed
}```

**Comment by nakupanda** [comment] 2015-09-16 03:07
It's weird.

http://jsfiddle.net/c7Lg0xwa/4/

Even with overflow-y: scroll; the page won't jump

**Comment by saqueib** [comment] 2015-09-16 03:22
Thanks @nakupanda 

I have updated fiddle with Bootstrap and weirdly its working with `overflow-y:scroll;` on 

http://jsfiddle.net/c7Lg0xwa/5/

But this jumping issue was fixed once i removed `html { overflow-y: scroll;}` in my code which uses a lot of other css

**Comment by nakupanda** [comment] 2015-09-16 03:45
No problem. 

Closing this issue as you have found a solution and it doesn't seem to be a bug.

**Closed by nakupanda** 2015-09-16 03:45 UTC
