### ISSUE TITLE
BootstrapDialog.confirm ignores options cssClass: and id:

### ISSUE THREAD

**Issue by uvesten** [nakupanda/bootstrap3-dialog#297] opened 2016-09-08 09:44 UTC
See example here:

http://jsfiddle.net/z7h4c12n/

**Comment by waspinator** [comment] 2016-09-09 18:43
I don't see any css or id options in your fiddle.

**Comment by uvesten** [comment] 2016-09-16 17:00
Neither do I when clicking the link now. Sigh

**Comment by waspinator** [comment] 2016-09-17 13:46
Could you try to fix it to show the problem? Otherwise maybe close the issue for now.

**Comment by nakupanda** [comment] 2016-09-19 02:55
@uvesten , I understand the problem, I will check current implementation and see how to improve it.

**Comment by nakupanda** [comment] 2016-09-19 02:55
I labelled this issue an enhancement rather than a bug.

**Comment by nakupanda** [comment] 2016-09-22 06:20
OK, I got the cause. The id and cssClass options being ignored because you're using old version of the library.

See a updated version: http://jsfiddle.net/42a9cztw/1/

**Comment by nakupanda** [comment] 2016-09-22 06:22
Making the import statement refers to bootstrap3-dialog v1.35.3 should fix your problem.

**Closed** 2016-09-22 06:21 UTC
Labels: enhancement

**Comment by uvesten** [comment] 2016-09-30 19:58
Thanks! Sorry for the slow response from my side!
