### ISSUE TITLE
BUG SOLVED

### ISSUE THREAD

**Issue by franciscocsysteames** [nakupanda/bootstrap3-dialog#331] opened 2017-02-23 22:02 UTC
If on the line 1075 you add next BootstrapDialog.moveFocus();  the next code:

if ($('.modal').hasClass('in')) {
                $('body').addClass('modal-open');
            }

you solution the problem with scroll of the another open modals

**Comment by nakupanda** [comment] 2017-02-24 06:28
Hi,

Can you create a demo showing the problem?

You can fork this demo: http://jsfiddle.net/o5k0eaws/1/

**Comment by franciscocsysteames** [comment] 2017-02-24 09:14
You can see the error on http://jsfiddle.net/o5k0eaws/315/

When the dialog is hidden the modal scroll brake.

but if you add 

if ($('.modal').hasClass('in')) {
$('body').addClass('modal-open');
}
on the line 1075 you add next BootstrapDialog.moveFocus(); the next code:

**Comment by franciscocsysteames** [comment] 2017-02-24 09:15
sorry, try it  the error http://jsfiddle.net/o5k0eaws/318/

**Comment by franciscocsysteames** [comment] 2017-02-24 09:18
this.getModal().on('hidden.bs.modal', {dialog: this}, function (event) {
                var dialog = event.data.dialog;
                dialog.isModalEvent(event) && typeof dialog.options.onhidden === 'function' && dialog.options.onhidden(dialog);
                if (dialog.isAutodestroy()) {
                    dialog.setRealized(false);
                    delete BootstrapDialog.dialogs[dialog.getId()];
                    $(this).remove();
                }
                BootstrapDialog.moveFocus();
                **if ($('.modal').hasClass('in')) {
                    $('body').addClass('modal-open');
                }**
            });

**Comment by nakupanda** [comment] 2017-03-01 08:32
Thanks for the demo, now I understood.

Mixing BootstrapDialog and original method could cause that kind of problem, but which is not a BUG of BootstrapDialog I think..

**Comment by fenichelar** [comment] 2017-03-23 13:30
This is a major problem for us. We use Ember Bootstrap for modals with forms because it is Ember data compatible. We use this to display errors when you submit. For pages with long forms (so long modals), after an error, you can't ever scroll again. Bootstrap Dialogs (or any front end library) should not alter elements on the DOM that it didn't create, I would call this a bug.

**Comment by nakupanda** [comment] 2017-03-24 01:25
@fenichelar , @franciscocsysteames 

Thanks for your efforts, PR merged, new release published, you can get it here https://github.com/nakupanda/bootstrap3-dialog/releases/tag/v1.35.4

**Closed by nakupanda** 2017-03-24 01:25 UTC
